### ISSUE TITLE
Tags are not added as separate tags

### ISSUE THREAD

**Issue by jon-rei** [takumakume/sbomreport-to-dependencytrack#3]
Hi,
thank you very much for building the sbom delivery to dependencytrack. This is something we have been looking for.

While setting it up I found that if multiple tags are defined like this: `projectTags: "tag1,tag2"`. 
They do not get added as individual tags in dependencytrack. My expectation would be that these two tags would be converted to individual tags in the dependency track.

**Comment by takumakume** [comment]
In my environment, I have operated it with one label, but I have not confirmed its operation with multiple labels.
I will check and take action.

**Comment by takumakume** [comment]
Thank you for your report.
New version 0.0.7 released!
