### ISSUE TITLE
Ability to add additional labels to the deployment

### ISSUE THREAD

**Issue by jon-rei** [takumakume/sbomreport-to-dependencytrack#4]
It would be great if additional labels could be added to the sbomreport-to-dependencytrack deployment. If you want, I can raise a PR myself.

**Comment by takumakume** [comment]
Thank you for using it!
Created `deploymentLabels` in helm.

https://github.com/takumakume/sbomreport-to-dependencytrack/pull/5

**Comment by jon-rei** [comment]
Hi thanks a lot for implementing so quickly.
I think I have expressed myself incorrectly, I need the ability to add the label to the pod in the deployment. Does it needs to be added here: https://github.com/takumakume/sbomreport-to-dependencytrack/blob/main/helm/sbomreport-to-dependencytrack/templates/deployment.yaml#L19?
I apologise again for expressing myself incorrectly.

**Comment by takumakume** [comment]
@jon-rei 
I understand!
I fixed it and released 0.0.8. 
https://github.com/takumakume/sbomreport-to-dependencytrack/pull/7
