### ISSUE TITLE
Constant increase of requests against Dependencytrack

### ISSUE THREAD

**Issue by jon-rei** [takumakume/sbomreport-to-dependencytrack#8]
We have been running sbomreport-to-dependencytrack on our clusters for some time. What we can see is that after a dependencytrack restart, the ingress requests are constantly increasing.
[In the code](https://github.com/takumakume/sbomreport-to-dependencytrack/blob/main/dependencytrack/dependencytrack.go#L56) I can see that the readiness for uploads is checked every second. Would it be possible to make the interval configurable or even add a timeout? I have a suspicion (but cannot really prove it) that the readiness checks are sometimes running indefinitely.

I could see the requests rising to 4.000 requests/s. For relevance we are managing ~3k projects in Dependencytrack.
<img width="954" alt="Screenshot 2023-12-05 at 09 16 44" src="https://github.com/takumakume/sbomreport-to-dependencytrack/assets/21036205/7697e793-bc10-462e-8370-8fa3d3bed8cb">

I can also raise a PR myself for those features.

**Comment by jon-rei** [comment]
Thanks for implementing this so quickly.
I think what's missing now is making these new configs configurable through helm.

**Comment by takumakume** [comment]
@jon-rei 

Thank you for the report!
> <.sbomReport.report.artifact.tag>: map has no entry for key "tag".

It doesn't occur in my environment.
Can I receive the SBOMReport when this error occurs? Please also tell me the version of trivy-operator.


> Could it be that the check for the SBOM readiness is not properly aborted?


- When you look at the Dependency Track access log, can you see the breakdown for each endpoint?
- How many requests are there for this software compared to the number of webhook requests for Trivy Operator after SBOMReport generation?

others. This software will send the SBOM again if it receives a webhook even if it has been sent once. Therefore, if you prevent retransmission with cache, etc., there is a possibility that it will improve to some extent.

---

By the way, is it used in DeepL's infrastructure? I think there are a lot of 3000 projects, so I'm interested!

**Comment by jon-rei** [comment]
Hi @takumakume,
Sorry for taking so long to get back to you.
We've now rebuilt our dependency track from scratch, and since then the constant increase in requests has gone away and hasn't happened again.
I think it was just a weird behaviour of our old setup.
I'd suspect the dependency track itself if it happened again.
Thanks again for helping out so quickly. By the way, we use dependencytrack to collect SBOMs of all the images running in the cluster.

**Comment by takumakume** [comment]
Thanks!!
